---
title: Clinic99.com
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@clinic99.com
description: We're building the best National Sexual Health Clinic Software on the Planet.
baseurl: ''
url: ''
minima:
  date_format: "%-d %b %Y"
theme: minima
plugins:
- jekyll-seo-tag
- jekyll-sitemap
